// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hrdnjajshuaroctlgcro.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhyZG5qYWpzaHVhcm9jdGxnY3JvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzkxMDU0ODIsImV4cCI6MjA1NDY4MTQ4Mn0.a8nJ31dZIP4oQNrRHenC6TV7dRfg8UegMREyg5Vkuqo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);